---
############################
############################
## GitHub Releases Action ##
############################
############################
name: Releases

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

###############################
# Start the job on tag pushes #
###############################
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

############
# Set Jobs #
############
jobs:

  releases:
    # Name the Job
    name: Releases
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:

      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      #########################
      # Create GitHub Release #
      #########################
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ./release.md
          draft: false
          prerelease: true

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      ################
      # Install Deps #
      ################
      - name: Install Deps
        shell: bash
        run: npm install
      
      #################
      # Build Package #
      #################
      - name: Build Package
        shell: bash
        run: npm run build:npm

      ###################
      # Publish Package #
      ###################
      - name: Publish Package
        shell: bash
        run: |
          cd publish
          npm publish
        