---
#########################
#########################
## GitHub Tests Action ##
#########################
#########################
name: Tests

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

##############################
# Start the job on all pulls #
##############################
on:
  push:
  pull_request:
    branches: [main]

############
# Set Jobs #
############
jobs:

  tests:
    # Name the Job
    name: Tests
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:

      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      ##############
      # Setup Node #
      ##############
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      ################
      # Install Deps #
      ################
      - name: Install Deps
        shell: bash
        run: npm install

      #################
      # Build Project #
      #################
      - name: Build Project
        shell: bash
        run: npm run build

      ################
      # Start Server #
      ################
      - name: Start Server
        shell: bash
        timeout-minutes: 1
        run: |
          npm run start

      #############
      # Run Tests #
      #############
      - name: Run Tests
        shell: bash
        run: |
          npm run test